//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFIntellectus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsolicitudamistad
    {
        public int IdSolicitudAmistad { get; set; }
        public int IdSolicitante { get; set; }
        public int IdSolicitado { get; set; }
        public string Estado { get; set; }
    }
}
